project:
  name: AIS-Based District-Level Electrical Motor Pump Adoption Pattern Analysis
  optimization: Artificial Immune System
  random_state: 42
dataset:
  path: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption Pattern
    Analysis\5.49.csv
  rows: 39
  columns: 9
  target: Electrical Motor Pump Use (%)
ais:
  population_size: 30
  generations: 30
  clone_factor: 5
  elite_size: 5
  mutation_rate: 0.15
  random_injection: 5
  best_fitness: 0.9874999999999999
  features_before: 4
  features_after: 1
  selected_features:
  - 'No'
model:
  type: AIS Optimized Feedforward Neural Network
  framework: TensorFlow Keras
  classes:
  - High Adoption
  - Low Adoption
  - Moderate Adoption
  accuracy: 0.9
  precision: 0.8099999999999999
  recall: 0.9
  f1_score: 0.8526315789473683
outputs:
  model: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption Pattern
    Analysis\ais_electrical_motor_pump_model.h5
  preprocessor: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption
    Pattern Analysis\ais_electrical_motor_pump_preprocessor.pkl
  json: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption Pattern
    Analysis\ais_electrical_motor_pump_metadata.json
  result_csv: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption
    Pattern Analysis\ais_result.csv
  prediction_csv: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption
    Pattern Analysis\ais_prediction.csv
  comparison_csv: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption
    Pattern Analysis\ais_model_comparison.csv
  feature_selection_csv: C:\Users\sagni\Downloads\District-Level Electrical Motor
    Pump Adoption Pattern Analysis\ais_feature_selection.csv
  fitness_history_csv: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump
    Adoption Pattern Analysis\ais_fitness_history.csv
  accuracy_graph: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption
    Pattern Analysis\ais_accuracy_graph.png
  loss_graph: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption
    Pattern Analysis\ais_loss_graph.png
  comparison_graph: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump
    Adoption Pattern Analysis\ais_comparison_graph.png
  heatmap: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption
    Pattern Analysis\ais_heatmap.png
  result_graph: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption
    Pattern Analysis\ais_result_graph.png
  prediction_graph: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump
    Adoption Pattern Analysis\ais_prediction_graph.png
  feature_selection_graph: C:\Users\sagni\Downloads\District-Level Electrical Motor
    Pump Adoption Pattern Analysis\ais_feature_selection_graph.png
  fitness_graph: C:\Users\sagni\Downloads\District-Level Electrical Motor Pump Adoption
    Pattern Analysis\ais_fitness_graph.png
